on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Vulnerabilities check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for vulnerabilities
        id: checks
        uses: maddygoround/secrets-not-allowed@main
      - name: Get results of scan
        run: echo "Scan Results - ${{ steps.checks.outputs.result }}"